/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/tasks': {
    /** Получить все задачи (с фильтрацией) */
    get: {
      parameters: {
        query?: {
          isImportant?: boolean;
          name_like?: string;
          isCompleted?: boolean;
        };
      };
      responses: {
        /** @description Успешное получение списка задач */
        200: {
          content: {
            'application/json': components['schemas']['Task'][];
          };
        };
      };
    };
    /** Создать новую задачу */
    post: {
      requestBody?: {
        content: {
          'application/json': components['schemas']['CreateTaskDto'];
        };
      };
      responses: {
        /** @description Задача успешно создана */
        201: {
          content: {
            'application/json': components['schemas']['Task'];
          };
        };
      };
    };
  };
  '/tasks/{id}': {
    /** Получить задачу по ID */
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Успешное получение задачи */
        200: {
          content: {
            'application/json': components['schemas']['Task'];
          };
        };
      };
    };
    /** Удалить задачу */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Задача успешно удалена */
        200: {
          content: {
            'application/json': {
              success?: boolean;
              id?: string;
            };
          };
        };
      };
    };
    /** Обновить задачу */
    patch: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['UpdateTaskDto'];
        };
      };
      responses: {
        /** @description Задача успешно обновлена */
        200: {
          content: {
            'application/json': components['schemas']['Task'];
          };
        };
      };
    };
    parameters: {
      path: {
        id: string;
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Task: {
      id: string;
      title: string;
      description: string;
      isCompleted?: boolean;
      isImportant?: boolean;
    };
    CreateTaskDto: {
      title: string;
      description: string;
      isCompleted?: boolean;
      isImportant?: boolean;
    };
    UpdateTaskDto: {
      title?: string;
      description?: string;
      isCompleted?: boolean;
      isImportant?: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
